tenants:
  tenant-alpha:
    name: "tenant-alpha"
    rpm_config:
      yard-availability: 100
      trailer-overview: 150
      trailer-exception-summary: 80
      task-workload-summary: 120
      task-attention-summary: 90
      site-occupancy: 110
      shipment-volume-forecast: 70
      dwell-time-summary: 85
      door-breakdown-summary: 95
      detention-summary: 75
      saved-filter-trailer-count: 60
    data_pool:
      facility_ids: [1001, 1002, 1003, 1004, 1005]
      carrier_ids: [2001, 2002, 2003, 2004, 2005, 2006]
      user_ids: [3001, 3002, 3003]
      saved_filter_ids: [4001, 4002, 4003, 4004]
    auth:
      token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
    sla:
      response_time_ms: 2000
      error_rate_percent: 1

  tenant-beta:
    name: "tenant-beta"
    rpm_config:
      yard-availability: 80
      trailer-overview: 120
      trailer-exception-summary: 60
      task-workload-summary: 100
      task-attention-summary: 70
      site-occupancy: 90
      shipment-volume-forecast: 50
      dwell-time-summary: 65
      door-breakdown-summary: 75
      detention-summary: 55
      saved-filter-trailer-count: 45
    data_pool:
      facility_ids: [2001, 2002, 2003]
      carrier_ids: [3001, 3002, 3003, 3004]
      user_ids: [4001, 4002]
      saved_filter_ids: [5001, 5002, 5003]
    auth:
      token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
    sla:
      response_time_ms: 2500
      error_rate_percent: 2

  tenant-gamma:
    name: "tenant-gamma"
    rpm_config:
      yard-availability: 120
      trailer-overview: 180
      trailer-exception-summary: 100
      task-workload-summary: 140
      task-attention-summary: 110
      site-occupancy: 130
      shipment-volume-forecast: 90
      dwell-time-summary: 105
      door-breakdown-summary: 115
      detention-summary: 95
      saved-filter-trailer-count: 75
    data_pool:
      facility_ids: [3001, 3002, 3003, 3004]
      carrier_ids: [4001, 4002, 4003, 4004, 4005]
      user_ids: [5001, 5002, 5003, 5004]
      saved_filter_ids: [6001, 6002, 6003, 6004, 6005]
    auth:
      token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
    sla:
      response_time_ms: 1500
      error_rate_percent: 0.5