scenarios:
  smoke_test:
    name: "Smoke Test"
    description: "Quick validation of all endpoints"
    duration_minutes: 5
    ramp_up_seconds: 30
    tenants: ["tenant-alpha"]
    load_multiplier: 0.1  # 10% of configured RPM

  load_test:
    name: "Load Test"
    description: "Standard load test at expected capacity"
    duration_minutes: 60
    ramp_up_seconds: 300
    tenants: ["tenant-alpha", "tenant-beta", "tenant-gamma"]
    load_multiplier: 1.0  # 100% of configured RPM

  stress_test:
    name: "Stress Test"
    description: "Push system beyond normal capacity"
    duration_minutes: 30
    ramp_up_seconds: 180
    tenants: ["tenant-alpha", "tenant-beta", "tenant-gamma"]
    load_multiplier: 1.5  # 150% of configured RPM

  endurance_test:
    name: "Endurance Test"
    description: "Extended duration test for memory leaks"
    duration_minutes: 240
    ramp_up_seconds: 600
    tenants: ["tenant-alpha", "tenant-beta"]
    load_multiplier: 0.8  # 80% of configured RPM

  spike_test:
    name: "Spike Test"
    description: "Sudden load increase simulation"
    duration_minutes: 20
    ramp_up_seconds: 5
    tenants: ["tenant-alpha", "tenant-beta", "tenant-gamma"]
    load_multiplier: 2.0  # 200% of configured RPM
